### PR TITLE
Release 4.1.0.

### PR DESCRIPTION
**Pull request by dwsteele**
- Add PostgreSQL 17 support.
- Remove support for PostgreSQL < 12.

We now have release notes in three separate places: GitHub releases, README.md, and CHANGELOG.txt. They are all different and I'd rather just standardize on Github release notes.

### CODE REVIEW

**Comment by dwsteele** [comment]
BTW, I'm not planning to put `rc*` in the control file and create update scripts for RC versions. Just seems like a lot of churn with little or no benefit. Nobody should be running RC releases in production.

**Review by artemgavrilov — APPROVED** [review]
🔥

**Review by keithf4 — CHANGES_REQUESTED** [review]
Update file looks good. Agreed on not providing updates on anything except mainline releases.

I agree the release notes can be left out of the readme. However, I do think they should still be in the repo as a file somewhere. For partman, I changed the CHANGELOG format to a markdown file. So now I can just copy-n-paste the same values from there into the release notes for the release. So the CHANGELOG is still the main location for all changes and users can still have access the entire change history from one easy to read place.
https://github.com/pgpartman/pg_partman/blob/master/CHANGELOG.md?plain=1

**Comment by dwsteele** [comment]
> However, I do think they should still be in the repo as a file somewhere.

I'm not too convinced by this. Lots of projects do not provide a top-level change log -- notably PostgreSQL. Multiple copies of the same data tend to get out of sync, which is what has already happened in set_user.

However, to move this along I've merged the release notes from README.md and CHANGELOG.txt into CHANGELOG.md. These notes are already out of sync with the Github release notes, but I'm not motivated to go back through and make those match. My vote would still be to nuke CHANGELOG.md entirely.

**Comment by farasulii** [comment]
547906569489350657 Reaction Roles Utils#5743j 2025-06-27T12:14:18.831Z -> Σ:1073.811s, Δ:0.001s -> RpcApplicationLogger -> 12306[]()

**Pull request merged**
