### PR TITLE
Add files for 4.0.0RC1 version upgrade

### PR DESCRIPTION
**Pull request by keithf4**
@mpalmi 

Saw the issue requesting a release that includes PG15 support. Looking at all the updates done since 3.0, it seems they were all non-SQL related. Please correct me if I'm wrong.

Copied one of the other files for the format used for a non-sql update. Should then allow tagging a new release.

### CODE REVIEW

**Comment by mpalmi** [comment]
Thanks @keithf4!

**Comment by keithf4** [comment]
@mpalmi 

Actually looking back on the issues that were fixed, would this be a 4.0 release with the GUC changes being undone? Does this release break some backward compatibility without manual intervention?

Is there anything else you wanted to get done before the next release? Or is this ok to merge, tag and release then?

**Comment by keithf4** [comment]
Also noticed the releases/tags are being done with a three number version but the actual extension only has a two number. Any objections to making this an actual 3 numbered semantic version?

**Comment by mpalmi** [comment]
I was leaning toward making the release a 4.0. No objections to a 3 numbered semantic version -- I agree. I was working on addressing some static analysis findings, but that shouldn't hold up the tag/release.

I made you admin, since things have been hectic over here lately and I likely won't be able to get to this until the weekend. Feel free to ping me with any questions.

Thanks!

**Comment by mpalmi** [comment]
We should definitely merge the deprecated GUC changes before we release. Looks like those haven't gone in yet!

**Comment by keithf4** [comment]
@mpalmi No rush in getting this out today. Next week would be fine. Posted a response in the deprecation PR when you have a moment.

**Comment by keithf4** [comment]
@mpalmi 

Updated files for next version to be 4.0.0rc1. I left it still copying the 3.0.sql file in the Makefile so its easy to test a 3.0 upgrade to 4.x. 

I might see about re-arranging things a bit more like the pg_partman extension so the Makefile doesn't need to be updated every new version if there's no objection. Can wait until later tho.

**Comment by keithf4** [comment]
@mpalmi Sorry meant to also ask you in that last update if there was anything else you wanted to get done for this release?

Would you mind doing a bullet list of features for the 4.x release? Looks like there were some other commits since 3.0 so just a short feature/bugfix list would be great.

Also, any idea why the 12-15 automated tests failed? Seems like they're looking for a folder that doesn't exist but prior version tests didn't seem to care.

**Comment by mpalmi** [comment]
> I might see about re-arranging things a bit more like the pg_partman extension so the Makefile doesn't need to be updated every new version if there's no objection. Can wait until later tho.

Sounds good. You can probably resurrect [this issue](https://github.com/pgaudit/set_user/issues/16) for that work.

> @mpalmi Sorry meant to also ask you in that last update if there was anything else you wanted to get done for this release?

I wanted to merge the clang-tidy fixes, but since CI is failing, I can't do that yet. See below.

> Would you mind doing a bullet list of features for the 4.x release? Looks like there were some other commits since 3.0 so just a short feature/bugfix list would be great.

For the past releases I've just used git history with some modification to generate the changelog. I can get back to you on that later.

> Also, any idea why the 12-15 automated tests failed? Seems like they're looking for a folder that doesn't exist but prior version tests didn't seem to care.

The missing folder is a side-effect of the root cause, which seems to be bad healthchecks in the set_user docker container. I'm really not sure why this is happening. I was looking into it last night. Will have to get back to it when I have some time.

**Comment by keithf4** [comment]
> > @mpalmi Sorry meant to also ask you in that last update if there was anything else you wanted to get done for this release?
> 
> I wanted to merge the clang-tidy fixes, but since CI is failing, I can't do that yet. See below.
> 
> > Would you mind doing a bullet list of features for the 4.x release? Looks like there were some other commits since 3.0 so just a short feature/bugfix list would be great.
> 
> For the past releases I've just used git history with some modification to generate the changelog. I can get back to you on that later.
> 
> > Also, any idea why the 12-15 automated tests failed? Seems like they're looking for a folder that doesn't exist but prior version tests didn't seem to care.
> 
> The missing folder is a side-effect of the root cause, which seems to be bad healthchecks in the set_user docker container. I'm really not sure why this is happening. I was looking into it last night. Will have to get back to it when I have some time.

Ok. I'll see about getting RC1 tagged on Wednesday. Give you some time to see if CI stuff can be fixed, but if not, this will still just be an RC so can maybe squeeze it in before final release.

**Pull request merged**
