### PR TITLE
Reorganized repository structure

### PR DESCRIPTION
**Pull request by keithf4**
Reorganized structure of repository to make managing of files easier for the build process. Adapted from methods used in https://github.com/pgpartman/pg_partman.

Updates moved into `updates` folder
C code moved into `src` folder
SQL code moved into `sql` folder
Moved test sql script into `test` folder and renamed for clarity compared to the extension core code file

Removed testing for versions of PostgreSQL no longer in community support

### CODE REVIEW

**Comment by keithf4** [comment]
@mpalmi Trying to do some reorg on this to make it a little easier to maintain going forward. I did move the C files into their own directory like I have on pg_partman and running `make install` seems to work ok for me using PGXS but doesn't seem to be working in the github testing. Will try and mess around and see if I can figure it out, but any assistance would be great. Thanks!

**Comment by keithf4** [comment]
I got 12 - 15 passing now. Learned all about pg_regress!

Looks like 11 is still failing because that is no longer available from where this is pulling PG from for the images?

**Review by pgguru — COMMENTED** [review]
So just to confirm, this is failing in the same way as the pre-reorg (i.e., PG 11 only). Do we just want to remove the `pgver` for 11 in the matrix, or is coverage there important enough to figure things out (and presumably get a new Docker image as a base)?

**Comment by keithf4** [comment]
> So just to confirm, this is failing in the same way as the pre-reorg (i.e., PG 11 only). Do we just want to remove the `pgver` for 11 in the matrix, or is coverage there important enough to figure things out (and presumably get a new Docker image as a base)?

Yes, it's failing in the same way it currently fails with the released version. I don't see anything in the code that's specific to 11, so it's not lacking in a code coverage sense if we excluded it. Importance of coverage there I think would really fall on the team that's primarily doing the development work on this extension.

**Comment by keithf4** [comment]
> > So just to confirm, this is failing in the same way as the pre-reorg (i.e., PG 11 only). Do we just want to remove the `pgver` for 11 in the matrix, or is coverage there important enough to figure things out (and presumably get a new Docker image as a base)?
> 
> Yes, it's failing in the same way it currently fails with the released version. I don't see anything in the code that's specific to 11, so it's not lacking in a code coverage sense if we excluded it. Importance of coverage there I think would really fall on the team that's primarily doing the development work on this extension.

Looked into this a bit more. This is using the github hosted runners for the regression test workflows. This only has Ubuntu as a target Linux OS (was going to try switching to something RHEL based if possible). 

https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners

Looks like if we really need to keep PG11 as part of this testing, we'd have to switch to a self-hosted runner since the ones that Github provides are what-you-see-is-what-you-get. 

Removed PG11 testing for now to see how the result would look and it's all green now. Let me know if there's another way you'd like to move forward with this.

**Comment by pgguru** [comment]
> > > So just to confirm, this is failing in the same way as the pre-reorg (i.e., PG 11 only). Do we just want to remove the `pgver` for 11 in the matrix, or is coverage there important enough to figure things out (and presumably get a new Docker image as a base)?
> > 
> > 
> > Yes, it's failing in the same way it currently fails with the released version. I don't see anything in the code that's specific to 11, so it's not lacking in a code coverage sense if we excluded it. Importance of coverage there I think would really fall on the team that's primarily doing the development work on this extension.
> 
> Looked into this a bit more. This is using the github hosted runners for the regression test workflows. This only has Ubuntu as a target Linux OS (was going to try switching to something RHEL based if possible).
> 
> https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners
> 
> Looks like if we really need to keep PG11 as part of this testing, we'd have to switch to a self-hosted runner since the ones that Github provides are what-you-see-is-what-you-get.
> 
> Removed PG11 testing for now to see how the result would look and it's all green now. Let me know if there's another way you'd like to move forward with this.

Assuming the pg 11 is only test coverage and not support, I’m personally fine with keeping the GH coverage unless there are reasons/approval/infra to setup our own runner.

**Review by pgguru — APPROVED** [review]

**Pull request merged**
